<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function wmprotected_vocabulary_form_alter(&$form, FormStateInterface $formState, $formId)
{
    /* @var \Drupal\wmprotected_vocabulary\Form\VocabularyFormAlter $configFormService */
    $configFormService = \Drupal::service('wmprotected_taxonomy.vocabulary_form_alter');
    $configFormService->alterForm($form, $formState, $formId);

    /* @var \Drupal\wmprotected_vocabulary\Form\TermDeleteFormAlter $deleteFormService */
    $deleteFormService = \Drupal::service('wmprotected_taxonomy.term_delete_form_alter');
    $deleteFormService->alterForm($form, $formState, $formId);
}
