<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\wmprotected_vocabulary\Form\TermDeleteFormAlter;
use Drupal\wmprotected_vocabulary\Form\VocabularyFormAlter;

function wmprotected_vocabulary_form_alter(array &$form, FormStateInterface $formState, string $formId)
{
    /* @var VocabularyFormAlter $configFormService */
    $configFormService = \Drupal::service('wmprotected_taxonomy.vocabulary_form_alter');
    $configFormService->alterForm($form, $formState, $formId);

    /* @var TermDeleteFormAlter $deleteFormService */
    $deleteFormService = \Drupal::service('wmprotected_taxonomy.term_delete_form_alter');
    $deleteFormService->alterForm($form, $formState, $formId);
}
